_core/urls.py
from django.contrib import admin
from django.urls import path, include
from cbv import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('cbv/', include('cbv.urls', namespace='cbv'))
]

cbv/urls.py
from django.urls import path
from cbv.views import (
    SchoolListView,
    SchoolDetailView,
    StudentListView,
    SchoolCreateView,
    SchoolUpdateView,
SchoolDeleteView)

app_name = 'cbv'

urlpatterns = [
    path('', SchoolListView.as_view(), name='list'),
    path('students/', StudentListView.as_view(), name='students'),
    path('create/', SchoolCreateView.as_view(), name='create'),
    path('<pk>/update', SchoolUpdateView.as_view(), name='update'),
    path('<pk>/delete', SchoolDeleteView.as_view(), name='delete'),
    path('<pk>/', SchoolDetailView.as_view(), name='detail'),
]

cbv/models.py
from django.db import models
from django.urls import reverse


class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('cbv:detail', kwargs={'pk': self.pk})


class Student(models.Model):
    name = models.CharField(max_length=50)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, on_delete=models.CASCADE, related_name='students')

    def __str__(self):
        return self.name

cbv/views.py
# from django.shortcuts import render
from django.urls import reverse_lazy
from cbv.models import School, Student
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView)


class SchoolDeleteView(DeleteView):
    model = School
    success_url = reverse_lazy('cbv:list')


class SchoolUpdateView(UpdateView):
    model = School
    fields = ['name', 'principal']
    template_name = 'cbv/cbv_school_create.html'


class SchoolCreateView(CreateView):
    model = School
    fields = ['name', 'principal', 'location']
    template_name = 'cbv/cbv_school_create.html'


class StudentListView(ListView):
    context_object_name = 'students'
    template_name = 'cbv/cbv_student_list.html'
    model = Student


class SchoolListView(ListView):
    context_object_name = 'schools'
    template_name = 'cbv/cbv_school_list.html'
    model = School


class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = School
    template_name = 'cbv/cbv_school_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class IndexView(TemplateView):
    template_name = 'cbv/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['inject_me'] = 'This is a secret'
        return context

cbv/templates/cbv/cbv_base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <title>CBV Learning</title>
</head>
<body>


<nav>
    <div class="container">
        <div class="nav-wrapper">
            <a href="{% url 'index' %}" class="brand-logo">CBV</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="{% url 'cbv:list' %}">Schools</a></li>
                <li><a href="{% url 'cbv:create' %}">Add School</a></li>
                <li><a href="{% url 'cbv:students' %}">Students</a></li>
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}
    {% endblock %}
</div>

<!-- Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var elems = document.querySelectorAll('.modal');
        var instances = M.Modal.init(elems);
    });
</script>
</body>
</html>

cbv/templates/cbv/cbv_school_confirm_delete.html
{% extends 'cbv/cbv_base.html' %}

{% block content %}
    <h1></h1>

{% endblock %}

cbv/templates/cbv/cbv_school_create.html
{% extends 'cbv/cbv_base.html' %}

{% block content %}
    <h1>
        {% if not form.instance.pk %}
            Create School
        {% else %}
            Update School
        {% endif %}
    </h1>

    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn waves-effect waves-light" type="submit" name="action">Submit
        </button>
    </form>
{% endblock %}

cbv/templates/cbv/cbv_school_detail.html
{% extends 'cbv/cbv_base.html' %}

{% block content %}
    <h1>Welcome to the School Detail Page</h1>
    <div class="row">
        <div class="col s12 m6">
            <div class="card blue lighten-4">
                <div class="card-content">
                    <span class="card-title">{{ school_detail.name }}</span>
                    <p>Principal: {{ school_detail.principal }}</p>
                    <p>Location: {{ school_detail.location }}</p>
                    <br>
                    <ul class="collection with-header card blue lighten-4">
                        <li class="collection-header"><h4>Students:</h4></li>
                        {% for student in school_detail.students.all %}
                            <li class="collection-item">{{ student.name }} who is {{ student.age }} years old.</li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="card-action">
                    <a href="{% url 'cbv:update' school_detail.id %}" class="waves-effect waves-light btn">Update
                        School</a>
                    <a href="{% url 'cbv:list' %}" class="waves-effect waves-light btn">Back to list</a>
                    <!-- Modal Trigger -->
                    <button data-target="modal1" class="btn modal-trigger red">Delete School</button>

                    <!-- Modal Structure -->
                    <div id="modal1" class="modal pink lighten-2" style="width: 500px">
                        <div class="modal-content">
                            <h4>Deleting - {{ school_detail.name }}</h4>
                            <p>Are you sure you want to delete?</p>
                        </div>
                        <div class="modal-footer">
                            <form action="{% url 'cbv:delete' school_detail.id %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="modal-close btn waves-effect waves-light">Confirm Delete</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

cbv/templates/cbv/cbv_school_list.html
{% extends 'cbv/cbv_base.html' %}

{% block content %}
    <ul class="collection with-header">
        <li class="collection-header"><h4>Welcome to list of all the school.</h4></li>
        {% for school in schools %}
            <li class="collection-item"><a href="{% url 'cbv:detail' school.id %}">{{ school.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

cbv/templates/cbv/cbv_student_list.html
{% extends 'cbv/cbv_base.html' %}

{% block content %}
    <h1>Welcome to list of all the Students.</h1>
    <ol>
        {% for student in students %}
            <h3>
                <li>{{ student.name }}</li>
            </h3>
            <ul>
                <li><h6>Age: {{ student.age }}</h6></li>
                <li><h6>School:<a href="{% url 'cbv:detail' student.school.id %}"> {{ student.school }}</a></h6></li>
            </ul>
        {% endfor %}
    </ol>
{% endblock %}

templates/base/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <title>CBV Learning</title>
</head>
<body>


<nav>
    <div class="container">
        <div class="nav-wrapper">
            <a href="#" class="brand-logo">Logo</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="sass.html">Sass</a></li>
                <li><a href="badges.html">Components</a></li>
                <li><a href="collapsible.html">JavaScript</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% block content %}
    {% endblock %}
</div>

<!-- Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>

templates/cbv/index.html
{% extends 'cbv/cbv_base.html' %}

{% block content %}
    <h1>Home Page</h1>
{% endblock %}